---
name: uaa

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 4

addons:
- name: bosh-dns-aliases
  jobs:
  - name: bosh-dns-aliases
    release: bosh-dns-aliases
    properties:
      aliases:
        - domain: saml.service.uaa.internal
          targets:
          - query: 'q-s4'
            instance_group: saml
            deployment: uaa
            network: default
            domain: bosh
        - domain: ldap-server.service.uaa.internal
          targets:
          - query: 'q-s4'
            instance_group: ldap-server
            deployment: uaa
            network: default
            domain: bosh
        - domain: uaa.service.uaa.internal
          targets:
          - query: 'q-s4'
            instance_group: uaa
            deployment: uaa
            network: default
            domain: bosh
        - domain: uaa-oidc.service.uaa.internal
          targets:
          - query: 'q-s4'
            instance_group: uaa-oidc
            deployment: uaa
            network: default
            domain: bosh

instance_groups:
- name: postgres
  instances: 1
  azs: [z1, z2, z3]
  vm_type: default
  stemcell: default
  persistent_disk: 500
  networks:
  - name: default
  jobs:
  - name: postgres
    release: postgres
    provides:
      postgres: {as: idp_postgres}
    properties:
      databases:
        databases:
        - name: uaadb
          citext: true
        roles:
        - name: uaaadmin
          password: admin

- name: uaa
  instances: 1
  azs: [z1, z2, z3]
  vm_type: default
  stemcell: default
  persistent_disk: 500
  networks:
  - name: default
  jobs:
  - name: uaa
    release: uaa
    consumes:
      database: {from: idp_postgres}
    properties:
      encryption:
        active_key_label: 'key-1'
        encryption_keys:
          - label: 'key-1'
            passphrase: 'MY-PASSPHRASE'
          - label: 'key-2'
            passphrase: 'MY-PASSPHRASE-TWO'
      uaadb:
        databases:
        - name: uaadb
          tag: uaa
        db_scheme: postgresql
        port: 5432
        roles:
        - name: uaaadmin
          password: admin
          tag: admin
      uaa:
        url: https://uaa.service.uaa.internal:8443
        jwt:
          policy:
            active_key_id: key-1
            keys:
              key-1:
                signingKey: ((uaa-key1.private_key))
        sslCertificate: ((uaa_tls.certificate))
        sslPrivateKey: ((uaa_tls.private_key))
        clients:
          admin:
            authorized-grant-types: 'urn:ietf:params:oauth:grant-type:jwt-bearer,authorization_code,client_credentials,refresh_token,user_token,password,urn:ietf:params:oauth:grant-type:saml2-bearer,implicit'
            redirect-uri: https://google.com
            scope: uaa.admin,clients.read,clients.write,clients.secret,scim.read,scim.write,clients.admin,uaa.user,openid
            authorities: uaa.admin,clients.admin
            secret: adminsecret
        scim:
          user:
            override: true
          users:
            - name: admin
              password: PASSWORD
              groups:
                - uaa.admin
            - name: marissa
              password: koala
              groups:
                - uaa.user
        #login:
        #  client_secret: PASSWORD
      login:
        protocol: https
        saml:
          activeKeyId: key1
          keys:
            key1:
              key: ((saml-key1.private_key))
              passphrase: ''
              certificate: ((saml-key1.certificate))
  - name: bpm
    release: bpm

variables:
  - name: uaa-key1
    type: rsa
  - name: uaa_ca
    type: certificate
    options:
      is_ca: true
      common_name: uaa
      alternative_names: ["*.uaa.service.uaa.internal"]
      extended_key_usage:
      - server_auth
  - name: saml-key1
    type: certificate
    options:
      ca: uaa_ca
      common_name: saml-key1-common_name
  - name: uaa_tls
    type: certificate
    options:
      ca: uaa_ca
      common_name: uaa.service.uaa.internal

releases:
- name: uaa
  url: https://bosh.io/d/github.com/cloudfoundry/uaa-release
  version: latest
- name: bosh-dns-aliases
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=0.0.3
  version: 0.0.3
  sha1: b0d0a0350ed87f1ded58b2ebb469acea0e026ccc
- name: postgres
  version: "34"
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=34
  sha1: d4e8993d5052c425692a71ea4ad43e7d9a113a4b
- name: bpm
  version: 1.0.4
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.4
  sha1: 41df19697d6a69d2552bc2c132928157fa91abe0

stemcells:
- alias: default
  os: ubuntu-xenial
  version: "latest"
